/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, IsEnum, ValidateNested } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { EnumLearningPathLevel } from "./EnumLearningPathLevel";
import { ProgressReportListRelationFilter } from "../../progressReport/base/ProgressReportListRelationFilter";
import { ScenarioListRelationFilter } from "../../scenario/base/ScenarioListRelationFilter";

@InputType()
class LearningPathWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    enum: EnumLearningPathLevel,
  })
  @IsEnum(EnumLearningPathLevel)
  @IsOptional()
  @Field(() => EnumLearningPathLevel, {
    nullable: true,
  })
  level?: "Option1";

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  mentor?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ProgressReportListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ProgressReportListRelationFilter)
  @IsOptional()
  @Field(() => ProgressReportListRelationFilter, {
    nullable: true,
  })
  progressReports?: ProgressReportListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ScenarioListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ScenarioListRelationFilter)
  @IsOptional()
  @Field(() => ScenarioListRelationFilter, {
    nullable: true,
  })
  scenarios?: ScenarioListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  students?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  title?: StringNullableFilter;
}

export { LearningPathWhereInput as LearningPathWhereInput };
