/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, IsEnum, ValidateNested } from "class-validator";
import { EnumLearningPathLevel } from "./EnumLearningPathLevel";
import { ProgressReportCreateNestedManyWithoutLearningPathsInput } from "./ProgressReportCreateNestedManyWithoutLearningPathsInput";
import { Type } from "class-transformer";
import { ScenarioCreateNestedManyWithoutLearningPathsInput } from "./ScenarioCreateNestedManyWithoutLearningPathsInput";

@InputType()
class LearningPathCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumLearningPathLevel,
  })
  @IsEnum(EnumLearningPathLevel)
  @IsOptional()
  @Field(() => EnumLearningPathLevel, {
    nullable: true,
  })
  level?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  mentor?: string | null;

  @ApiProperty({
    required: false,
    type: () => ProgressReportCreateNestedManyWithoutLearningPathsInput,
  })
  @ValidateNested()
  @Type(() => ProgressReportCreateNestedManyWithoutLearningPathsInput)
  @IsOptional()
  @Field(() => ProgressReportCreateNestedManyWithoutLearningPathsInput, {
    nullable: true,
  })
  progressReports?: ProgressReportCreateNestedManyWithoutLearningPathsInput;

  @ApiProperty({
    required: false,
    type: () => ScenarioCreateNestedManyWithoutLearningPathsInput,
  })
  @ValidateNested()
  @Type(() => ScenarioCreateNestedManyWithoutLearningPathsInput)
  @IsOptional()
  @Field(() => ScenarioCreateNestedManyWithoutLearningPathsInput, {
    nullable: true,
  })
  scenarios?: ScenarioCreateNestedManyWithoutLearningPathsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  students?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;
}

export { LearningPathCreateInput as LearningPathCreateInput };
